cd Paul_Execution_Results
start Paul_Execution_1.bat
start Paul_Execution_2.bat
start Paul_Execution_3.bat
start Paul_Execution_4.bat
start Paul_Execution_5.bat
start Paul_Execution_6.bat
start Paul_Execution_7.bat
start Paul_Execution_8.bat
start Paul_Execution_9.bat
start Paul_Execution_10.bat
start Paul_Execution_11.bat
start Paul_Execution_12.bat
start Paul_Execution_13.bat
start Paul_Execution_14.bat
start Paul_Execution_15.bat
start Paul_Execution_16.bat
start Paul_Execution_17.bat
start Paul_Execution_18.bat
start Paul_Execution_19.bat
start Paul_Execution_20.bat
start Paul_Execution_21.bat